main: me.ikevoodoo.helix.BukkitHelixProvider
name: "Helix"
description: "A plugin loader which adds extra features on top of Spigot"
version: '${version}'
api-version: 1.17
author: IkeVoodoo
website: "https://refinedtech.dev/discord"

libraries:
  - info.debatty:java-string-similarity:2.0.0
  - com.google.code.gson:gson:${lib.gson.ver}
  - com.github.zafarkhaja:java-semver:${lib.semver.ver}